# Streamlit configuration file
[server]
enableStaticServing = true

[browser]
gatherUsageStats = false

[runner]
fastReruns = true

[theme]
primaryColor = "#4CAF50"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"
